config/routes.rb
Rails.application.routes.draw do
  root 'leagues#index'
  devise_for :users

  resources :leagues do
    resources :membership_requests, only: :create
    resources :memberships, only: [ :create, :destroy ]
    resources :league_weeks, only: :show
    resources :league_picks, only: :show
  end

  resources :league_weeks, only: :show do
    resources :league_picks, only: [ :new, :create ]
  end
end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :user
  has_many :membership_requests, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :league_weeks, dependent: :destroy
  has_many :league_games, dependent: :destroy

  after_create :create_league_weeks
  after_create :create_league_owner
  after_create :create_league_games

  validates :title,
    presence: true,
    uniqueness: true

  # def is_league_member(user)
  #   memberships.find_by(user_id: user.id, league_id: params[:id])
  # end

  # def is_league_owner
  #   current_user && Membership.find_by(league: params[:id], owner: true)
  # end

  private

  def create_league_weeks
    Week.all.each do |week|
      self.league_weeks.create(week: week)
    end
  end

  def create_league_owner
    Membership.create(owner: true, user: League.last.user, league: self)
  end

  def create_league_games
    games = Game.all
    league_weeks = LeagueWeek.where(league_id: self.id)

    games.each do |g|
      league_weeks.each do |lw|
        if g.week_id == lw.week_id
          LeagueGame.create(league_id: lw.league_id,
                            league_week_id: lw.id,
                            game_id: g.id,
                            day: g.day,
                            date: g.date,
                            visitor_team: g.visitor_team,
                            home_team: g.home_team,
                            time: g.time)
        end
      end
    end
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def index
    @leagues = League.all
  end

  def show
    @league = League.find(params[:id])
    @requests = @league.membership_requests
    @members = Membership.where(league_id: params[:id])
    @owner = Membership.find_by(user: current_user, league_id: params[:id], owner: true)
    @league_weeks = LeagueWeek.where(league_id: params[:id])
  end

  def new
    @league = League.new
  end

  def create
    @league = League.new(league_params)
    @league.user = current_user

    if @league.save
      redirect_to league_path(@league)
      flash[:notice] = "Your league has been successfully created."
    else
      render :new
    end
  end

  def edit
    @league = League.find(params[:id])
  end

  def update
    @league = League.find(params[:id])

    if @league.update_attributes(league_params)
      redirect_to league_path(@league)
      flash[:notice] = "Your league has been successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @league = current_user.leagues.find(params[:id])
    @league.destroy
    flash[:notice] = "Your league has been deleted."
    redirect_to root_path
  end

  private

  def league_params
    params.require(:league).permit(:title, :description)
  end
end

app/views/leagues/_edit_league_form.html.erb
<%= form_for @league do |f| %>

  <div class="field">
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </div>

  <%= f.submit %>

<% end %>

app/views/leagues/_new_league_form.html.erb
<%= form_for @league do |f| %>

  <div class="field">
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </div>

  <%= f.submit %>

<% end %>

app/views/leagues/edit.html.erb
<h3>Fill out the form to edit your Pick 'Em League</h3>

<%= render "edit_league_form" %>

app/views/leagues/index.html.erb
<% @leagues.each do |league| %>
  <p class="index-league-title"><%= link_to league.title, league_path(league) %></p>
<% end %>

app/views/leagues/new.html.erb
<h2>Fill out the form to create a new Pick 'Em League</h2>

<%= render "new_league_form" %>

app/views/leagues/show.html.erb
<h3><%= @league.title %></h3>

<p>League Owner: <%= @league.user.name %></p>

<% if current_user != @league.user %>

  <p><%= link_to 'Join League', league_membership_requests_path(@league), method: :post %></p>

<% else %>

  <h5><%= link_to 'Edit Your League', edit_league_path(@league) %></h5>
  <h5><%= link_to 'Delete League', league_path(@league), method: :delete %></h5>

  <% @requests.each do |request| %>
    <p><%= request.user.username %></p>
    <p><%= link_to 'Approve Request', league_memberships_path(request.user_id), method: :post %></p>
  <% end %>

<% end %>

<p>Description:</p>
<p><%= @league.description %></p>

<% @members.each do |member| %>
  <p><%= member.user.name %></p>
  <% if current_user == member.user %>
    <p><%= link_to 'Leave League', league_membership_path(@league, member), method: :delete %></p>
  <% end %>
<% end %>

<% @league_weeks.each do |league_week| %>
  <%= link_to "Make Week #{league_week.week_id} Picks", new_league_week_league_pick_path(league_week) %>
<% end %>